import { useEffect, useState } from 'react';
import { api, makeSlug, readFileAsDataUrl } from '../api/apiClient';
import { useLang } from '../components/LanguageContext';

const blank = { id:'', name:{en:'',ar:''}, categoryId:'', desc:{en:'',ar:''}, image:'/assets/images/products/books.jpg' };
export default function ProductsAdmin() {
  const { lang, tr } = useLang();
  const [products, setProducts] = useState([]);
  const [categories, setCategories] = useState([]);
  const [editing, setEditing] = useState(null);
  useEffect(() => { Promise.all([api.products.list(), api.categories.list()]).then(([p,c]) => { setProducts(p); setCategories(c); }).catch(console.error); }, []);
  const open = (p=null) => setEditing(p ? JSON.parse(JSON.stringify(p)) : { ...blank, id:'', categoryId: categories[0]?.id || '' });
  const save = async (e) => { e.preventDefault(); const item = { ...editing, id: editing.id || makeSlug(editing.name.en) }; const saved = products.some(p => p.id === item.id) ? await api.products.update(item.id, item) : await api.products.create(item); setProducts(products.some(p => p.id === saved.id) ? products.map(p => p.id === saved.id ? saved : p) : [saved, ...products]); setEditing(null); };
  const remove = async (id) => { await api.products.remove(id); setProducts(products.filter(p => p.id !== id)); };
  const file = async (f) => { if (!f) return; const data = await readFileAsDataUrl(f); setEditing({ ...editing, image:data.dataUrl }); };
  return <div><div className="admin-top"><div><span className="eyebrow">Admin Portal</span><h1>{tr('adminProducts')}</h1><p>Add, edit and delete products shown on the client products page.</p></div><button className="btn primary" onClick={() => open()}>+ Add product</button></div><div className="table-card"><table><thead><tr><th>Image</th><th>Name</th><th>Category</th><th>{tr('actions')}</th></tr></thead><tbody>{products.map(p => { const cat = categories.find(c => c.id === p.categoryId); return <tr key={p.id}><td><img className="thumb" src={p.image} /></td><td><b>{p.name?.[lang]}</b><br/><span className="muted">{p.desc?.[lang]}</span></td><td>{cat?.name?.[lang]}</td><td><button className="btn light" onClick={() => open(p)}>Edit</button> <button className="btn light danger-text" onClick={() => remove(p.id)}>Delete</button></td></tr>; })}</tbody></table></div>{editing && <div className="modal-backdrop" onMouseDown={() => setEditing(null)}><form className="modal-card modal-clean" onMouseDown={e => e.stopPropagation()} onSubmit={save}><div className="modal-head"><h2>{editing.id ? 'Edit product' : 'Add product'}</h2><button className="icon-btn" type="button" onClick={() => setEditing(null)}>×</button></div><div className="form-grid"><div className="form-field"><label>Name EN*</label><input required value={editing.name.en} onChange={e => setEditing({...editing, name:{...editing.name,en:e.target.value}})} /></div><div className="form-field"><label>Name AR</label><input value={editing.name.ar} onChange={e => setEditing({...editing, name:{...editing.name,ar:e.target.value}})} /></div><div className="form-field"><label>Category</label><select value={editing.categoryId} onChange={e => setEditing({...editing, categoryId:e.target.value})}>{categories.map(c => <option key={c.id} value={c.id}>{c.name?.[lang]}</option>)}</select></div><div className="form-field"><label>Image</label><input type="file" accept="image/*" onChange={e => file(e.target.files?.[0])}/></div><div className="form-field full"><label>Description EN</label><textarea value={editing.desc.en} onChange={e => setEditing({...editing, desc:{...editing.desc,en:e.target.value}})} /></div><div className="form-field full"><label>Description AR</label><textarea value={editing.desc.ar} onChange={e => setEditing({...editing, desc:{...editing.desc,ar:e.target.value}})} /></div></div><button className="btn primary" type="submit">{tr('save')}</button></form></div>}</div>;
}
