import { useEffect, useState } from 'react';
import { api, makeSlug } from '../api/apiClient';
import { useLang } from '../components/LanguageContext';

const blank = { id:'', username:'', fullName:'', email:'', password:'', role:'Sales', isActive:true };
export default function Users() {
  const { tr } = useLang();
  const [users, setUsers] = useState([]);
  const [editing, setEditing] = useState(null);
  useEffect(() => { api.users.list().then(setUsers).catch(console.error); }, []);
  const open = (u=null) => setEditing(u ? JSON.parse(JSON.stringify(u)) : { ...blank });
  const save = async (e) => { e.preventDefault(); const item = { ...editing, id: editing.id || `u-${makeSlug(editing.username)}` }; const saved = users.some(u => u.id === item.id) ? await api.users.update(item.id, item) : await api.users.create(item); setUsers(users.some(u => u.id === saved.id) ? users.map(u => u.id === saved.id ? saved : u) : [saved, ...users]); setEditing(null); };
  const remove = async (id) => { await api.users.remove(id); setUsers(users.filter(u => u.id !== id)); };
  return <div><div className="admin-top"><div><span className="eyebrow">Admin Portal</span><h1>{tr('users')}</h1><p>Add, edit and delete admin portal users. Passwords are plain only for prototype; backend can be changed to hashes later.</p></div><button className="btn primary" onClick={() => open()}>+ Add user</button></div><div className="table-card"><table><thead><tr><th>Username</th><th>Full name</th><th>Email</th><th>Role</th><th>Status</th><th>{tr('actions')}</th></tr></thead><tbody>{users.map(u => <tr key={u.id}><td><b>{u.username}</b></td><td>{u.fullName}</td><td>{u.email}</td><td>{u.role}</td><td>{u.isActive ? 'Active' : 'Inactive'}</td><td><button className="btn light" onClick={() => open(u)}>Edit</button> <button className="btn light danger-text" onClick={() => remove(u.id)}>Delete</button></td></tr>)}</tbody></table></div>{editing && <div className="modal-backdrop" onMouseDown={() => setEditing(null)}><form className="modal-card modal-clean" onMouseDown={e => e.stopPropagation()} onSubmit={save}><div className="modal-head"><h2>{editing.id ? 'Edit user' : 'Add user'}</h2><button className="icon-btn" type="button" onClick={() => setEditing(null)}>×</button></div><div className="form-grid"><div className="form-field"><label>Username*</label><input required value={editing.username} onChange={e => setEditing({...editing, username:e.target.value})}/></div><div className="form-field"><label>Password*</label><input required value={editing.password} onChange={e => setEditing({...editing, password:e.target.value})}/></div><div className="form-field"><label>Full name</label><input value={editing.fullName} onChange={e => setEditing({...editing, fullName:e.target.value})}/></div><div className="form-field"><label>Email</label><input value={editing.email} onChange={e => setEditing({...editing, email:e.target.value})}/></div><div className="form-field"><label>Role</label><select value={editing.role} onChange={e => setEditing({...editing, role:e.target.value})}><option>Admin</option><option>Sales</option></select></div><div className="form-field checkbox-field"><label><input type="checkbox" checked={editing.isActive} onChange={e => setEditing({...editing, isActive:e.target.checked})}/> Active</label></div></div><button className="btn primary" type="submit">{tr('save')}</button></form></div>}</div>;
}
